server:
  port: 0

spring:
  application:
    name: eureka-client

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/